apiVersion: v2
name: pagopa-ecommerce-transactions-scheduler-service
description: Microservice that perform scheduled operations on pending transactions
type: application
version: 4.0.1
appVersion: 4.0.1
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
